//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSKStream.Classes_metier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_animer : Sommaire_series
    {
        public string Titre_animer { get; set; }
    
        public virtual Animer Animer { get; set; }
    }
}
