//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSKStream.Classes_metier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Films : Videos
    {
        public long Anne_production { get; set; }
        public System.DateTime Date_sortie { get; set; }
        public string Lien { get; set; }
    }
}
