//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSKStream
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Sommaire_series
    {
        public string Titre { get; set; }
        public long Saison { get; set; }
        public long Episode { get; set; }
        public string Lien { get; set; }
    }
}
