//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSKStream.Classes_metier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        public string Titre { get; set; }
        public string Acteure { get; set; }
        public string Genre { get; set; }
        public string Pays { get; set; }
        public System.TimeSpan Duree { get; set; }
        public string Creer_par { get; set; }
        public string Categorie { get; set; }
        public string Description { get; set; }
        public string Filefullname { get; set; }
    }
}
