//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSKStream
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video_serie : Videos
    {
        public long NBsaison { get; set; }
        public long NBepisode { get; set; }
        public long Annee_lancement { get; set; }
    }
}
